### ISSUE TITLE
Allow core API extensions that do not begin with `/1.0`.

### ISSUE THREAD

**Issue by markylaing** [canonical/microcluster#135]
LXD site manager will need to implement OIDC on the core API. To do this, some handlers need to be added to handle the auth flow. Currently it (appears to be) only possible to add handlers to `/1.0`, whereas it would be ideal to add these handlers under `/oidc` (e.g. `/oidc/login` as in LXD).

One way to do this would be to handle setting `Path` field in `rest.Endpoint` to a full path, e.g. with a leading forward slash.

**Comment by roosterfish** [comment]
Wouldn't this be supported when https://github.com/canonical/microcluster/pull/130 is merged? You could then add a server with arbitrary endpoints.

**Comment by markylaing** [comment]
It would be, but not for the core API, only on the extra listeners.

**Comment by masnax** [comment]
To recap the discussion in our meeting: I think it would be fine to allow this to be configurable by the user as long as we have proper validation that ensures the paths do not collide with internal API paths like `/internal`.
