### ISSUE TITLE
How do we pass `ExtensionServer` to microcluster upon initialisation?

### ISSUE THREAD

**Issue by mas-who** [canonical/microcluster#139]
PR #130 was merged recently, with it comes the ability to register many network listeners by passing `ExtensionServers` to microcluster via `microcluster.Args`. Given that each network listener need to have its own address specified, the list of servers should be constructed during initialisation based on user provided listener addresses. I can't seem to find a way to pass `ExtensionServers` to microcluster during initialisation since it is only being consumed in `MicroCluster.Start`. Not sure if I'm missing something?

**Comment by masnax** [comment]
I believe this should have been addressed by https://github.com/canonical/microcluster/pull/174
