### ISSUE TITLE
Make client request functionality more flexible

### ISSUE THREAD

**Issue by mas-who** [canonical/microcluster#170]
The [(client.Client).Query](https://github.com/canonical/microcluster/blob/ec0a2d6e0f31c63851ec416068f8e338cd910e09/client/client.go#L26) method is exposed to a downstream project for making client requests. A typical use case is forwarding requests to a different cluster member.

This method currently constructs the `http.Request` object internally, which is restrictive for certain use cases. For example, if we want to  forward a request with cookies, we would have to extract the cookies from its header and send them as part of the payload to a newly defined `POST` endpoint. Ideally if the query method could allow passing in a `http.Request` object, then this would enable more use cases due to added flexibility.

The same goes for returning a response object from the client query method so that we can access more than just the response payload. AFAIK the `(client.Client).Query` method currently only supports writing the response data to a provided struct.

**Comment by masnax** [comment]
Closed by https://github.com/canonical/microcluster/pull/164
