### ISSUE TITLE
Having `(microcluster.MicroCluster).RemoteClient` defined for `state.State`

### ISSUE THREAD

**Issue by mas-who** [canonical/microcluster#171]
AFAIK in microcluster we can send client requests by using `(client.Cluster).Query`, setting `rest.EndpointAction.ProxyTarget=true` and `(microcluster.MicroCluster).RemoteClient`. 

If we want to send a request to a specific member, `(client.Cluster).Query` is not the best option since it would establish a client connection with every cluster member. 

Using `ProxyTarget=true` on an endpoint will work as long as the `target` query parameter is specified. This doesn't work in the scenario where we can't add the `target` query param to the request url. Using oidc authentication as an example, the request url is set on the idp end and the only query params that may exist in the url should be `code` and `state`. 

This leaves us with the last option, using `(microcluster.MicroCluster).RemoteClient` which works. However, a downstream project would need to pass the the `MicroCluster` struct to an endpoint, which can be achieved by setting it on a locally defined state struct like what's shown below.
```
type SiteManagerState struct {
	MicroCluster *microcluster.MicroCluster
}
```
Although it works, but it feels a bit strange since we could expose a method similar to `(microcluster.MicroCluster).RemoteClient` in state, then endpoints would have the ability to establish a specific client out of the box which I think could be a good improvement?

**Comment by roosterfish** [comment]
@mas-who maybe I cannot follow but you don't have to pass the `*microcluster.MicroCluster` around in your own state struct.

If you want to use `RemoteClient()` from any of your endpoints, you can create a new instance of `*microcluster.MicroCluster` using `App()` and then run either `LocalClient()` (which gives you a connection to the local Unix socket) or `RemoteClient()` to connect to any other cluster member directly.

**Comment by mas-who** [comment]
> @mas-who maybe I cannot follow but you don't have to pass the `*microcluster.MicroCluster` around in your own state struct.
> 
> If you want to use `RemoteClient()` from any of your endpoints, you can create a new instance of `*microcluster.MicroCluster` using `App()` and then run either `LocalClient()` (which gives you a connection to the local Unix socket) or `RemoteClient()` to connect to any other cluster member directly.

Aah yes, we can pass the state dir arg using `state.State.FileSystem().StateDir`. The recent cleanup with `microcluster.Args` also would make this code nice, thanks! Will adjust this in cluster manager, closing this issue.
