### ISSUE TITLE
Add join token expiration

### ISSUE THREAD

**Issue by masnax** [canonical/microcluster#199]
Join tokens exist forever after creation. Instead, we should have some mechanism to expire tokens after a user-specified period of time.

This means updating the join token configuration [here](https://github.com/canonical/microcluster/blob/e7fce6564cbe708e198a6e644696dc5ab7f72b2c/microcluster/app.go#L277-L289) to take a timeout. 

There are a few nuances here like changing the schema to expect an initial creation date for tokens.

**Comment by masnax** [comment]
I'm not sure how LXD handles image expiry, but I'm thinking in microcluster a good place to handle this would be when issuing a heartbeat.

**Comment by masnax** [comment]
There's also the matter of deciding if we want a sensible default expiration, like a minute per token by default.

**Comment by MggMuggins** [comment]
https://documentation.ubuntu.com/lxd/en/latest/server/#server-core:core.remote_token_expiry
