### ISSUE TITLE
Allow `OnHeartbeat` hook to identify Dqlite role changes

### ISSUE THREAD

**Issue by roosterfish** [canonical/microcluster#209]
It might be helpful to indicate Dqlite role changes inside the `OnHearbeat` hook so that members can learn about their current role inside the cluster and can properly react on changes.

**Comment by masnax** [comment]
We'll want to extend the [OnHeartbeat hook](https://github.com/canonical/microcluster/blob/688a4bc5d3f865506a782d0bdc5d299813b14dbe/internal/state/hooks.go#L36) with a new slice in the function signature. 

The slice should have an entry for each cluster member, with a way to determine if its role has changed. There are a few ways to do this. 

* We could add a new type here that contains the `name`, `old_role`, and `new_role` for each cluster member.
* We could extend [ClusterMember.Role](https://github.com/canonical/microcluster/blob/688a4bc5d3f865506a782d0bdc5d299813b14dbe/rest/types/cluster.go#L12) to be a new `ClusterRole` type with a `NewRole` and `OldRole` fields, as well as a `String() string` helper which just returns `NewRole` and a `Changed() bool` which checks if `NewRole != OldRole`. 
* Most simplistically, we can just pass two maps: `map[string]string`  keyed by cluster member name, with the value being the roles.
