### ISSUE TITLE
"Forbidden" database errors are silently ignored

### ISSUE THREAD

**Issue by petrutlucian94** [canonical/microcluster#240]
Let's asume a Canonical K8s (snap) cluster with invalid certificates. When starting k8sd, we'll get "Forbidden" errors. The problem is that:

* those errors are not logged
* microcluster returns status code 200 instead of 403
  * https://github.com/canonical/microcluster/blob/9da23064cf0ad86768e05db4695a9d239bb717c1/internal/rest/rest.go#L246-L255 

This significantly hinders the debugging process since the k8sd logs will not contain any relevant messages. All we get is that the dialing failed as it expected a protocol switch (101) but got 200 (why not 403?) https://github.com/canonical/microcluster/blob/42551841a56dd2d4697d577428bdb4d7d5f877d0/internal/db/dqlite.go#L441

**Comment by roosterfish** [comment]
Can you please elaborate on what do you mean with invalid certificates? Have you changed the underlying certificates used by microcluster (server/cluster.crt)?

A few lines above the request handler is rewritten to `handleDatabaseRequest` which hijacks the request and hands over the `net.Conn` to dqlite. 
Then dqlite upgrades the connection to websocket.

After the connection got hijacked the authority on the `net.Conn` was given up so we cannot anymore read/write from/to the connection in the API handler.
I suspect that is the reason for the `e.Path != database` check.

**Comment by petrutlucian94** [comment]
> Can you please elaborate on what do you mean with invalid certificates? Have you changed the underlying certificates used by microcluster (server/cluster.crt)?

The node was using the server/cluster.crt certificates of another node since the state dir was placed on a drbd device that got mounted as part of the failover process. I also noticed that the certificates from the trust store were being replaced upon restarting the k8s snap services.

> After the connection got hijacked the authority on the net.Conn was given up so we cannot anymore read/write from/to the connection in the API handler.
I suspect that is the reason for the e.Path != database check.

I see. To be honest, I didn't dig further to see where the 200 status code came from, but I think at the very least it would be a good idea to log some info or debug messages. For example here, that would be extremely useful for debugging purposes: https://github.com/canonical/microcluster/blob/9da23064cf0ad86768e05db4695a9d239bb717c1/internal/rest/rest.go#L135-L146

**Comment by roosterfish** [comment]
AFAIK the 200 is the default that gets written to the `http.ResponseWriter` in case nobody else wrote something to it.
But most likely this is only happening in case the connection didn't got hijacked. 

So in order to properly forward the error responses from the `handleDatabaseRequest` func, I am wondering if we should check for the type of `resp` returned in `HandleEndpoint`. 
Both database API handlers return an `EmptySyncResponse` so we can potentially extend the condition to still return the actual response in case `resp` is not of type `EmptySyncResponse`:

```go
if e.Path == "database" && resp != response.EmptySyncResponse {
    // connection wasn't upgraded, return the actual response
}

if e.Path != "database" {
    // return as usual
}
```
