### ISSUE TITLE
Let `db.NewDB` return an interface to allow mocking the DB

### ISSUE THREAD

**Issue by roosterfish** [canonical/microcluster#245]
When writing unit tests for the API endpoints it would be helpful if we could mock the database instance returned by `db.NewDB`.
By returning an interface we can create a `dbMock` struct and assign it to the `state.InternalState` struct by setting the `InternalDatabase` field.

This allows fast unit testing as we can easily supply a mocked state to the API handlers.

**Comment by masnax** [comment]
We have this now.

**Comment by roosterfish** [comment]
> We have this now.

Can you please elaborate on this? `NewDB` still returns a struct https://github.com/canonical/microcluster/blob/v3/internal/db/dqlite.go#L76.

**Comment by roosterfish** [comment]
The `State` interface's [`Database()`](https://github.com/canonical/microcluster/blob/05863eb0b1f64e37456fbf8467c0bcc8497f25ea/internal/state/state.go#L43) returns the [`DB`](https://github.com/canonical/microcluster/blob/v3/internal/db/interface.go#L14) interface which allows easy mocking.

Ty @masnax
