### ISSUE TITLE
Not able to remove server from cluster with name provided during add operation

### ISSUE THREAD

**Issue by hemanthnakkina** [canonical/microcluster#57]
Added a server to the cluster with name microceph/14 and not able to use the same name to remove the server.

Error message:
No remote exists with the given name "microceph%2F14"

Expectation is to be able to use the same name provided during add operation for delete operation as well.
If the basic assumption is name should be hostname, it should spell out explicitly in documentation and help.

Note: ``microceph cluster list`` shows the servers with hostname instead of name provided during add operation.

Steps to reproduce:
```
sudo microceph cluster add microceph/14
sudo microceph cluster join <token>
sudo microceph cluster remove microceph/14
```

**Comment by stgraber** [comment]
Relocating the issue to microcluster so @masnax can work on a fix.
In this case the fix should be that we don't allow creating entries that include slashes. Maybe we should send this through the hostname validation logic same as we use for instance names in LXD?

**Comment by MggMuggins** [comment]
Closing as we now require cluster member names to pass [this function](https://github.com/canonical/lxd/blob/main/shared/validate/validate.go#L715). @hemanthnakkina Based on the testing I've done it doesn't seem possible (anymore?) for a cluster member with a forward slash in the name to join the cluster completely (see #106).
