### ISSUE TITLE
Synchronization issue between `onJoin` and `onNewMember`

### ISSUE THREAD

**Issue by mkalcok** [canonical/microcluster#60]
I think that `onNewMember` hook is fired on existing cluster members before `onJoin` hook finishes on the joining member. I've ran into this sync/timing issue specifically in [microovn](https://github.com/canonical/microovn) however I believe that the root cause is here in `microcluster` code.

To understand the issue, following is important to know about `microovn`. It has:

- [`func Join`](https://github.com/canonical/microovn/blob/1177d409110cf76eb32b5e3773db58320e443c06/microovn/ovn/join.go#L15) associated with a [`onJoin` hook](https://github.com/canonical/microovn/blob/1177d409110cf76eb32b5e3773db58320e443c06/microovn/cmd/microovnd/main.go#L70) that populates database table `services` with information about which services are running on the joining cluster member.
- [`func Refresh`](https://github.com/canonical/microovn/blob/1177d409110cf76eb32b5e3773db58320e443c06/microovn/ovn/refresh.go#L16) associated with a [`onNewMember` hook](https://github.com/canonical/microovn/blob/1177d409110cf76eb32b5e3773db58320e443c06/microovn/cmd/microovnd/main.go#L71) that among other thing [generates environment file using contents of `services` table](https://github.com/canonical/microovn/blob/1177d409110cf76eb32b5e3773db58320e443c06/microovn/ovn/environment.go#L58).

The behavior that I'm observing is that when `Refresh` function calls `generateEnvironment` on existing cluster members, data that were supposed to be inserted by joining member are not in the database yet. If I artificially postpone execution of `generateEnvironment`, it's usually able to find expected data in the database.

How to reproduce the issue:

- Modify `microovn`
  - Add logging output that shows content of `sbConnect` and `nbConnect` variables around [here](https://github.com/canonical/microovn/blob/1177d409110cf76eb32b5e3773db58320e443c06/microovn/ovn/environment.go#L69). These variables are simply list of IPs and ports of other `microovn` members that run `ovn` services and are sourced from the database.
  - Add second execution of `generateEnvironment` at [the end of `Refresh` function](https://github.com/canonical/microovn/blob/1177d409110cf76eb32b5e3773db58320e443c06/microovn/ovn/refresh.go#L99). There's already one call to the `generateEnvironment` in `Refresh` function and the second call will demonstrate that this is a timing issue as the second call will be slightly delayed.
- Build modified `microovn`
- Install it on at least two nodes
- Bootstrap first cluster node and generate "join" token.
- Start watching logs of the `microovn.daemon` service on the node with bootstrapped cluster
- Join microovn cluster with a second node
- Observe the logging output generated by our modified code that outputs contents of `sbConnect` and `nbConnect` strings
  - First execution won't contain IP of a newly joined member
  - Second, slightly delayed, execution will contain IP of a newly joined member

**Comment by masnax** [comment]
We've already merged a fix for this since our discussion at the sprint :) 

The issue was that `OnJoin` was actually a bit vague in its description. It was only intended to be run after `OnNewMember` has run on all peers. Though that causes some inflexibility with `microcluster`.

So now, the `OnJoin` hook has been brought in line with the `remove` hooks, and is now replaced with `PreJoin` and `PostJoin` hooks which run on the newly added peer before and after `OnNewMember` runs on all other peers, respectively. 

Hope that helps :)
